//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./react_types');
//HELPER FUNCTIONS AND STRUCTURES

reactthrift.ReactThrift_renderComponentToString_args = function(args) {
  this.name = null;
  this.props = null;
  if (args) {
    if (args.name !== undefined) {
      this.name = args.name;
    }
    if (args.props !== undefined) {
      this.props = args.props;
    }
  }
};
reactthrift.ReactThrift_renderComponentToString_args.prototype = {};
reactthrift.ReactThrift_renderComponentToString_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.props = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

reactthrift.ReactThrift_renderComponentToString_args.prototype.write = function(output) {
  output.writeStructBegin('ReactThrift_renderComponentToString_args');
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 1);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.props !== null && this.props !== undefined) {
    output.writeFieldBegin('props', Thrift.Type.STRING, 2);
    output.writeString(this.props);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

reactthrift.ReactThrift_renderComponentToString_result = function(args) {
  this.success = null;
  this.err = null;
  if (args instanceof ttypes.ServerException) {
    this.err = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.err !== undefined) {
      this.err = args.err;
    }
  }
};
reactthrift.ReactThrift_renderComponentToString_result.prototype = {};
reactthrift.ReactThrift_renderComponentToString_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.err = new ttypes.ServerException();
        this.err.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

reactthrift.ReactThrift_renderComponentToString_result.prototype.write = function(output) {
  output.writeStructBegin('ReactThrift_renderComponentToString_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  if (this.err !== null && this.err !== undefined) {
    output.writeFieldBegin('err', Thrift.Type.STRUCT, 1);
    this.err.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

reactthrift.ReactThriftClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
reactthrift.ReactThriftClient.prototype = {};
reactthrift.ReactThriftClient.prototype.seqid = function() { return this._seqid; }
reactthrift.ReactThriftClient.prototype.new_seqid = function() { return this._seqid += 1; }
reactthrift.ReactThriftClient.prototype.renderComponentToString = function(name, props, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_renderComponentToString(name, props);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_renderComponentToString(name, props);
  }
};

reactthrift.ReactThriftClient.prototype.send_renderComponentToString = function(name, props) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('renderComponentToString', Thrift.MessageType.CALL, this.seqid());
  var args = new reactthrift.ReactThrift_renderComponentToString_args();
  args.name = name;
  args.props = props;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

reactthrift.ReactThriftClient.prototype.recv_renderComponentToString = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new reactthrift.ReactThrift_renderComponentToString_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.err) {
    return callback(result.err);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('renderComponentToString failed: unknown result');
};
reactthrift.ReactThriftProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
reactthrift.ReactThriftProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

reactthrift.ReactThriftProcessor.prototype.process_renderComponentToString = function(seqid, input, output) {
  var args = new reactthrift.ReactThrift_renderComponentToString_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.renderComponentToString.length === 2) {
    Q.fcall(this._handler.renderComponentToString, args.name, args.props)
      .then(function(result) {
        var result = new reactthrift.ReactThrift_renderComponentToString_result({success: result});
        output.writeMessageBegin("renderComponentToString", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new reactthrift.ReactThrift_renderComponentToString_result(err);
        output.writeMessageBegin("renderComponentToString", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.renderComponentToString(args.name, args.props,  function (err, result) {
      var result = new reactthrift.ReactThrift_renderComponentToString_result((err != null ? err : {success: result}));
      output.writeMessageBegin("renderComponentToString", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

