//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = module.exports = {};
if (typeof reactthrift === 'undefined') {
  reactthrift = {};
}
reactthrift.ServerException = module.exports.ServerException = function(args) {
  Thrift.TException.call(this, "reactthrift.ServerException")
  this.name = "reactthrift.ServerException"
  this.error = null;
  if (args) {
    if (args.error !== undefined) {
      this.error = args.error;
    }
  }
};
Thrift.inherits(reactthrift.ServerException, Thrift.TException);
reactthrift.ServerException.prototype.name = 'ServerException';
reactthrift.ServerException.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.error = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

reactthrift.ServerException.prototype.write = function(output) {
  output.writeStructBegin('ServerException');
  if (this.error !== null && this.error !== undefined) {
    output.writeFieldBegin('error', Thrift.Type.STRING, 1);
    output.writeString(this.error);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

